"""initial migration

Revision ID: 0876d3fae08c
Revises: 
Create Date: 2017-04-18 00:05:37.342161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0876d3fae08c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kind',
    sa.Column('phid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('k_name', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('phid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kind')
    # ### end Alembic commands ###
